import type { Candidate } from "./types"

export const mockCandidates: Candidate[] = [
  {
    id: "1",
    name: "Alex Johnson",
    email: "alex.johnson@email.com",
    yearsOfExperience: 5,
    skills: ["React", "Node.js", "TypeScript", "PostgreSQL"],
    technicalScore: 92,
    interviewScore: 88,
    cultureFitScore: 85,
    overallScore: 88,
    status: "pending",
  },
  {
    id: "2",
    name: "Sarah Chen",
    email: "sarah.chen@email.com",
    yearsOfExperience: 7,
    skills: ["React", "Next.js", "AWS", "MongoDB"],
    technicalScore: 95,
    interviewScore: 92,
    cultureFitScore: 90,
    overallScore: 92,
    status: "pending",
  },
  {
    id: "3",
    name: "Michael Brown",
    email: "michael.brown@email.com",
    yearsOfExperience: 4,
    skills: ["JavaScript", "Vue.js", "Firebase"],
    technicalScore: 85,
    interviewScore: 82,
    cultureFitScore: 88,
    overallScore: 85,
    status: "pending",
  },
  {
    id: "4",
    name: "Emily Davis",
    email: "emily.davis@email.com",
    yearsOfExperience: 6,
    skills: ["React", "Node.js", "GraphQL", "Docker"],
    technicalScore: 90,
    interviewScore: 89,
    cultureFitScore: 92,
    overallScore: 90,
    status: "pending",
  },
  {
    id: "5",
    name: "David Wilson",
    email: "david.wilson@email.com",
    yearsOfExperience: 3,
    skills: ["React", "JavaScript", "CSS"],
    technicalScore: 80,
    interviewScore: 78,
    cultureFitScore: 82,
    overallScore: 80,
    status: "pending",
  },
  {
    id: "6",
    name: "Jessica Miller",
    email: "jessica.miller@email.com",
    yearsOfExperience: 8,
    skills: ["React", "Next.js", "TypeScript", "AWS", "MongoDB"],
    technicalScore: 94,
    interviewScore: 91,
    cultureFitScore: 89,
    overallScore: 91,
    status: "pending",
  },
]
